### ISSUE TITLE
Complete Profile Page

### ISSUE THREAD

**Issue by luederb** [luederb/Phi-Effect#10]
**As a User**
**I need** complete my profile data
**to be able to** adapt my username etc. to this app

## Description

![Image](https://github.com/luederb/Phi-Effect/assets/136329211/41ca2ff5-e33f-4e6d-8ec5-17d7b2d2ff34)

## Acceptance Criteria
- [x] After the redirection of the google API, the complete profile page opens
- [x] In the form, the user can enter his name, email, phone number and bio
- [x] The `complete Sign Up` button opens the homepage (with login)

## Tasks
- [x] get the google-ID from the login element and save it to the user useState variable
- [x] save the form data to use States (controlled input fields) and push the data to the database
