### ISSUE TITLE
Homepage with and without login

### ISSUE THREAD

**Issue by luederb** [luederb/Phi-Effect#8]
**As a User**
**I need** know, what to do, when I open the app the first time
**to be able to** properly start using the app

## Description

![Image](https://github.com/luederb/Phi-Effect/assets/136329211/3ee7a10e-c7b0-48c6-83a2-9670da8d67f0)

## Acceptance Criteria
- [x] A welcome text is visible
- [x] two links direct the user to the projects and competitions
- [x] The user gets told, what he can do, when he signs in
- [x] a 'sign in' button is clickable
- [x] the 'sign in' button opens the google login API URL
- [x] after the successful authentication, the use is redirected to the 'complete profile' page

## Tasks
- [x] Use the Google API to authenticate the user
- [x] save the google-ID, name and password to the database
- [x] redirect the user to the 'complete profile' page
